"""
Demo message building.
"""
from x12.msg_271_4010_X092_A1 import *


def test_marshall() -> None:
    m = MSG271(
        isa_loop=[
            ISA_LOOP(
                isa=ISA_LOOP_ISA(
                    isa01=ISA_LOOP_ISA01("00"),
                    isa02=ISA_LOOP_ISA02("          "),
                    isa03=ISA_LOOP_ISA03("00"),
                    isa04=ISA_LOOP_ISA04("          "),
                    isa05=ISA_LOOP_ISA05("ZZ"),
                    isa06=ISA_LOOP_ISA06("ZIRMED         "),
                    isa07=ISA_LOOP_ISA07("ZZ"),
                    isa08=ISA_LOOP_ISA08("12345          "),
                    isa09=ISA_LOOP_ISA09("120605"),
                    isa10=ISA_LOOP_ISA10("2324"),
                    isa11=ISA_LOOP_ISA11("U"),
                    isa12=ISA_LOOP_ISA12("00401"),
                    isa13=ISA_LOOP_ISA13("000050033"),
                    isa14=ISA_LOOP_ISA14("1"),
                    isa15=ISA_LOOP_ISA15("P"),
                    isa16=ISA_LOOP_ISA16("^"),
                ),
                gs_loop=[
                    GS_LOOP(
                        gs=GS_LOOP_GS(
                            gs01=GS_LOOP_GS01("HB"),
                            gs02=GS_LOOP_GS02("ZIRMED"),
                            gs03=GS_LOOP_GS03("12345"),
                            gs04=GS_LOOP_GS04("20120605"),
                            gs05=GS_LOOP_GS05("2324"),
                            gs06=GS_LOOP_GS06("50025"),
                            gs07=GS_LOOP_GS07("X"),
                            gs08=GS_LOOP_GS08("004010X092A1"),
                        ),
                        st_loop=[
                            ST_LOOP(
                                st=ST_LOOP_ST(
                                    st01=ST_LOOP_ST01("271"), st02=ST_LOOP_ST02("0001")
                                ),
                                header=[
                                    HEADER(
                                        bht=HEADER_BHT(
                                            bht01=HEADER_BHT01("0022"),
                                            bht02=HEADER_BHT02("11"),
                                            bht03=HEADER_BHT03("11111"),
                                            bht04=HEADER_BHT04("20120605"),
                                            bht05=HEADER_BHT05("232423"),
                                        )
                                    )
                                ],
                                detail=[
                                    DETAIL(
                                        l2000a=[
                                            L2000A(
                                                hl=L2000A_HL(
                                                    hl01=L2000A_HL01("1"),
                                                    hl03=L2000A_HL03(""),
                                                    hl04=L2000A_HL04("20"),
                                                ),
                                                l2100a=[
                                                    L2100A(
                                                        nm1=L2100A_NM1(
                                                            nm101=L2100A_NM101("PR"),
                                                            nm102=L2100A_NM102("2"),
                                                            nm103=L2100A_NM103(
                                                                "Health Net Inc"
                                                            ),
                                                            nm104=L2100A_NM104(""),
                                                            nm105=L2100A_NM105(""),
                                                            nm107=L2100A_NM107(""),
                                                            nm108=L2100A_NM108(""),
                                                            nm109=L2100A_NM109("PI"),
                                                        )
                                                    )
                                                ],
                                                l2000b=[
                                                    L2000B(
                                                        hl=L2000B_HL(
                                                            hl01=L2000B_HL01("2"),
                                                            hl02=L2000B_HL02("1"),
                                                            hl03=L2000B_HL03("21"),
                                                            hl04=L2000B_HL04("1"),
                                                        ),
                                                        l2100b=[
                                                            L2100B(
                                                                nm1=L2100B_NM1(
                                                                    nm101=L2100B_NM101(
                                                                        "1P"
                                                                    ),
                                                                    nm102=L2100B_NM102(
                                                                        "2"
                                                                    ),
                                                                    nm103=L2100B_NM103(
                                                                        "DR. ACULA"
                                                                    ),
                                                                    nm104=L2100B_NM104(
                                                                        ""
                                                                    ),
                                                                    nm105=L2100B_NM105(
                                                                        ""
                                                                    ),
                                                                    nm107=L2100B_NM107(
                                                                        ""
                                                                    ),
                                                                    nm108=L2100B_NM108(
                                                                        ""
                                                                    ),
                                                                    nm109=L2100B_NM109(
                                                                        "XX"
                                                                    ),
                                                                )
                                                            )
                                                        ],
                                                        l2000c=[
                                                            L2000C(
                                                                hl=L2000C_HL(
                                                                    hl01=L2000C_HL01(
                                                                        "3"
                                                                    ),
                                                                    hl02=L2000C_HL02(
                                                                        "2"
                                                                    ),
                                                                    hl03=L2000C_HL03(
                                                                        "22"
                                                                    ),
                                                                    hl04=L2000C_HL04(
                                                                        "0"
                                                                    ),
                                                                ),
                                                                trn=[
                                                                    L2000C_TRN(
                                                                        trn01=L2000C_TRN01(
                                                                            "1"
                                                                        ),
                                                                        trn02=L2000C_TRN02(
                                                                            "222222222"
                                                                        ),
                                                                        trn03=L2000C_TRN03(
                                                                            "9ZIRMEDCOM"
                                                                        ),
                                                                        trn04=L2000C_TRN04(
                                                                            "ELR ID"
                                                                        ),
                                                                    ),
                                                                    L2000C_TRN(
                                                                        trn01=L2000C_TRN01(
                                                                            "2"
                                                                        ),
                                                                        trn02=L2000C_TRN02(
                                                                            "333333333"
                                                                        ),
                                                                        trn03=L2000C_TRN03(
                                                                            "9ZIRMEDCOM"
                                                                        ),
                                                                        trn04=L2000C_TRN04(
                                                                            "ELI ID"
                                                                        ),
                                                                    ),
                                                                    L2000C_TRN(
                                                                        trn01=L2000C_TRN01(
                                                                            "1"
                                                                        ),
                                                                        trn02=L2000C_TRN02(
                                                                            "4444444444"
                                                                        ),
                                                                        trn03=L2000C_TRN03(
                                                                            "9MEDDATACO"
                                                                        ),
                                                                        trn04=L2000C_TRN04(
                                                                            None
                                                                        ),
                                                                    ),
                                                                ],
                                                                l2100c=[
                                                                    L2100C(
                                                                        nm1=L2100C_NM1(
                                                                            nm101=L2100C_NM101(
                                                                                "IL"
                                                                            ),
                                                                            nm102=L2100C_NM102(
                                                                                "1"
                                                                            ),
                                                                            nm103=L2100C_NM103(
                                                                                ""
                                                                            ),
                                                                            nm104=L2100C_NM104(
                                                                                ""
                                                                            ),
                                                                            nm105=L2100C_NM105(
                                                                                ""
                                                                            ),
                                                                            nm106=L2100C_NM106(
                                                                                ""
                                                                            ),
                                                                            nm107=L2100C_NM107(
                                                                                ""
                                                                            ),
                                                                            nm108=L2100C_NM108(
                                                                                "MI"
                                                                            ),
                                                                            nm109=L2100C_NM109(
                                                                                "R11111111"
                                                                            ),
                                                                        ),
                                                                        aaa=[
                                                                            L2100C_AAA(
                                                                                aaa01=L2100C_AAA01(
                                                                                    "N"
                                                                                ),
                                                                                aaa03=L2100C_AAA03(
                                                                                    ""
                                                                                ),
                                                                                aaa04=L2100C_AAA04(
                                                                                    "72"
                                                                                ),
                                                                            ),
                                                                            L2100C_AAA(
                                                                                aaa01=L2100C_AAA01(
                                                                                    "N"
                                                                                ),
                                                                                aaa03=L2100C_AAA03(
                                                                                    ""
                                                                                ),
                                                                                aaa04=L2100C_AAA04(
                                                                                    "73"
                                                                                ),
                                                                            ),
                                                                            L2100C_AAA(
                                                                                aaa01=L2100C_AAA01(
                                                                                    "N"
                                                                                ),
                                                                                aaa03=L2100C_AAA03(
                                                                                    ""
                                                                                ),
                                                                                aaa04=L2100C_AAA04(
                                                                                    "73"
                                                                                ),
                                                                            ),
                                                                            L2100C_AAA(
                                                                                aaa01=L2100C_AAA01(
                                                                                    "N"
                                                                                ),
                                                                                aaa03=L2100C_AAA03(
                                                                                    ""
                                                                                ),
                                                                                aaa04=L2100C_AAA04(
                                                                                    "58"
                                                                                ),
                                                                            ),
                                                                        ],
                                                                        dtp=[
                                                                            L2100C_DTP(
                                                                                dtp01=L2100C_DTP01(
                                                                                    "291"
                                                                                ),
                                                                                dtp02=L2100C_DTP02(
                                                                                    "D8"
                                                                                ),
                                                                                dtp03=L2100C_DTP03(
                                                                                    "20120408"
                                                                                ),
                                                                            )
                                                                        ],
                                                                    )
                                                                ],
                                                            )
                                                        ],
                                                    )
                                                ],
                                            )
                                        ]
                                    )
                                ],
                                se=ST_LOOP_SE(
                                    se01=ST_LOOP_SE01("17"), se02=ST_LOOP_SE02("0001")
                                ),
                            )
                        ],
                        ge=GS_LOOP_GE(
                            ge01=GS_LOOP_GE01("1"), ge02=GS_LOOP_GE02("50025")
                        ),
                    )
                ],
                iea=ISA_LOOP_IEA(
                    iea01=ISA_LOOP_IEA01("1"), iea02=ISA_LOOP_IEA02("000050033")
                ),
            )
        ]
    )
    # print(m)
    assert m.isa_loop[0].isa.isa12.value == "00401"  # Interchange Control Version Number
    assert m.isa_loop[0].gs_loop[0].gs.gs08.value == "004010X092A1"  # Version / Release / Industry Identifier Code
    assert m.isa_loop[0].gs_loop[0].gs.gs01.value == "HB"  # Functional Identifier Code
    assert m.isa_loop[0].gs_loop[0].st_loop[0].st.st01.value == "271"
