insert into claims_benefit( benefit, description ) values ( 'AMSU', 'Ambulatory Surgical Center' );
insert into claims_benefit( benefit, description ) values ( 'INPT', 'Inpatient Care' );
insert into claims_benefit( benefit, description ) values ( 'IPDX', 'Alcohol & Substance Detox' );
insert into claims_benefit( benefit ) values ( 'MAMN' );
insert into claims_benefit( benefit ) values ( 'DME' );
insert into claims_benefit( benefit ) values ( 'SNF' );
insert into claims_benefit( benefit, description ) values ( 'ABOR', 'Abortion' );
insert into claims_benefit( benefit, description ) values ( 'ACCD', 'Accidental Dental' );
insert into claims_benefit( benefit ) values ( 'ACPR' );
insert into claims_benefit( benefit, description ) values ( 'ACUP', 'Accupuncture' );
insert into claims_benefit( benefit, description ) values ( 'AI', 'Aritificial Insemination' );
insert into claims_benefit( benefit, description ) values ( 'ALLI', 'Allergy Testing & Injections' );
insert into claims_benefit( benefit ) values ( 'ALLT' );
insert into claims_benefit( benefit ) values ( 'AMBA' );
insert into claims_benefit( benefit ) values ( 'AMBL' );
insert into claims_benefit( benefit ) values ( 'ANES' );
insert into claims_benefit( benefit ) values ( 'APPR' );
insert into claims_benefit( benefit ) values ( 'ASMD' );
insert into claims_benefit( benefit ) values ( 'ASPA' );
insert into claims_benefit( benefit ) values ( 'ASRC' );
insert into claims_benefit( benefit ) values ( 'ASRH' );
insert into claims_benefit( benefit ) values ( 'BD' );
insert into claims_benefit( benefit ) values ( 'CHEM' );
insert into claims_benefit( benefit ) values ( 'CHRC' );
insert into claims_benefit( benefit ) values ( 'CHRP' );
insert into claims_benefit( benefit, description ) values ( 'MRI', 'MRI/MRA');
insert into claims_benefit( benefit, description ) values ( 'OBEV', 'Observation / Acuity Evaluation');
insert into claims_benefit( benefit, description ) values ( 'OBSV', 'Observation Room');
insert into claims_benefit( benefit, description ) values ( 'ORTH', 'Orthotics');
insert into claims_benefit( benefit, description ) values ( 'OT', 'Rehabilitative Therapy - Occupational');
