#!/usr/bin/env python
from tigershark.X12.parse import Message
from tigershark.X12.parse import Loop
from tigershark.X12.parse import Segment
from tigershark.X12.parse import Composite
from tigershark.X12.parse import Element
from tigershark.X12.parse import Properties

parse_278 = Message( '278', Properties(desc='278'),
  Loop( 'ISA', Properties(req_sit='R',repeat='1',desc='ISA'),
    Segment( 'ISA', Properties(),
    Loop( 'GS', Properties(req_sit='R',repeat='1',desc='GS'),
      Segment( 'GS', Properties(),
      Loop( 'ST', Properties(req_sit='R',repeat='1',desc='ST'),
        Segment( 'ST', Properties(qual=(1, '278'),req_sit='R',repeat=1,desc='Transaction Set Header'),
        Segment( 'BHT', Properties(req_sit='R',repeat=1,desc='Beginning of Hierarchical Transaction'),
        Loop( '2000A', Properties(req_sit='R',repeat='1',desc='2000A'),
          Segment( 'HL', Properties(qual=(3, '20'),req_sit='R',repeat='1',desc='Utilization Management Organization (UMO) Level'),
          Loop( '2010A', Properties(req_sit='R',repeat='>1',desc='2010A'),
            Segment( 'NM1', Properties(qual=(1, 'X3'),req_sit='R',repeat='1',desc='Utilization Management Organization (UMO) Name'),
          ),
        ),
        Loop( '2000B', Properties(req_sit='R',repeat='1',desc='2000B'),
          Segment( 'HL', Properties(qual=(3, '21'),req_sit='R',repeat='1',desc='Requester Level'),
          Loop( '2010B', Properties(req_sit='R',repeat='>1',desc='2010B'),
            Segment( 'NM1', Properties(qual=(1, ('1P', 'FA')),req_sit='R',repeat='1',desc='Requester Name'),
            Segment( 'REF', Properties(req_sit='S',repeat='8',desc='Requester Supplemental Identification'),
            Segment( 'N3', Properties(req_sit='S',repeat='1',desc='Requester Address'),
            Segment( 'N4', Properties(req_sit='S',repeat='1',desc='Requester City/State/ZIP Code'),
            Segment( 'PER', Properties(req_sit='S',repeat='1',desc='Requester Contact Information'),
            Segment( 'PRV', Properties(req_sit='S',repeat='1',desc='Requester Provider Information'),
          ),
        ),
        Loop( '2000C', Properties(req_sit='R',repeat='1',desc='2000C'),
          Segment( 'HL', Properties(qual=(3, '22'),req_sit='R',repeat='1',desc='Subscriber Level'),
          Segment( 'DTP', Properties(req_sit='S',repeat=1,desc='Accident Date'),
          Segment( 'DTP', Properties(req_sit='S',repeat=1,desc='Last Menstrual Period Date'),
          Segment( 'DTP', Properties(req_sit='S',repeat=1,desc='Estimated Date of Birth'),
          Segment( 'DTP', Properties(req_sit='S',repeat=1,desc='Onset of Current Symptoms or Illness Date'),
          Segment( 'HI', Properties(req_sit='S',repeat=1,desc='Subscriber Diagnosis'),
          Loop( '2010C', Properties(req_sit='R',repeat='>1',desc='2010C'),
            Segment( 'NM1', Properties(qual=(1, 'IL'),req_sit='R',repeat=1,desc='Subscriber Name'),
            Segment( 'REF', Properties(req_sit='S',repeat=9,desc='Subscriber Supplemental Identification'),
            Segment( 'DMG', Properties(req_sit='S',repeat=1,desc='Subscriber Demographic Information'),
          ),
        ),
        Loop( '2000D', Properties(req_sit='R',repeat='1',desc='2000D'),
          Segment( 'HL', Properties(qual=(3, '23'),req_sit='S',repeat=1,desc='Dependent Level'),
          Segment( 'DTP', Properties(req_sit='S',repeat=1,desc='Accident Date'),
          Segment( 'DTP', Properties(req_sit='S',repeat=1,desc='Last Menstrual Period Date'),
          Segment( 'DTP', Properties(req_sit='S',repeat=1,desc='Estimated Date of Birth'),
          Segment( 'DTP', Properties(req_sit='S',repeat=1,desc='Onset of Current Symptoms or Illness Date'),
          Segment( 'HI', Properties(req_sit='S',repeat=1,desc='Dependent Diagnosis'),
          Loop( '2010D', Properties(req_sit='R',repeat='>1',desc='2010D'),
            Segment( 'NM1', Properties(qual=(1, 'QD'),req_sit='R',repeat=1,desc='Dependent Name'),
            Segment( 'REF', Properties(req_sit='S',repeat=3,desc='Dependent Supplemental Identification'),
            Segment( 'DMG', Properties(req_sit='S',repear=1,desc='Dependent Demographic Information'),
            Segment( 'INS', Properties(req_sit='S',repeat=1,desc='Dependent Relationship'),
          ),
        ),
        Loop( '2000E', Properties(req_sit='R',repeat='1',desc='2000E'),
          Segment( 'HL', Properties(qual=(3, '19'),req_sit='R',repeat=1,desc='Service Provider Level'),
          Segment( 'MSG', Properties(req_sit='S',repeat=1,desc='Message Text'),
          Loop( '2010E', Properties(req_sit='R',repeat='>1',desc='2010E'),
            Segment( 'NM1', Properties(qual=(1, ('1T', 'FA', 'SJ')),req_sit='R',repeat=1,desc='Service Provider Name'),
            Segment( 'REF', Properties(req_sit='S',repeat=7,desc='Service Provider Supplemental Identification'),
            Segment( 'N3', Properties(req_sit='S',repeat=1,desc='Service Provider Address'),
            Segment( 'N4', Properties(req_sit='S',repeat=1,desc='Service Provider City/State/ZIP Code'),
            Segment( 'PER', Properties(req_sit='S',repeat=1,desc='Service Provider Contact Information'),
            Segment( 'PRV', Properties(req_sit='S',repeat=1,desc='Service Provider Information'),
          ),
        ),
        Loop( '2000F', Properties(req_sit='R',repeat='1',desc='2000F'),
          Segment( 'HL', Properties(qual=(3, 'SS'),req_sit='R',repeat=1,desc='Service Level'),
          Segment( 'TRN', Properties(req_sit='S',repeat=2,desc='Service Trace Number'),
          Segment( 'UM', Properties(req_sit='R',repeat=1,desc='Health Care Services Review Information'),
          Segment( 'REF', Properties(req_sit='S',repeat=1,desc='Previous Certification Identification'),
          Segment( 'DTP', Properties(req_sit='S',repeat=1,desc='Service Date'),
          Segment( 'DTP', Properties(req_sit='S',repeat=1,desc='Admission Date'),
          Segment( 'DTP', Properties(req_sit='S',repeat=1,desc='Discharge Date'),
          Segment( 'DTP', Properties(req_sit='S',repeat=1,desc='Surgery Date'),
          Segment( 'HI', Properties(req_sit='S',repeat=1,desc='Procedures'),
          Segment( 'HSD', Properties(req_sit='S',repeat=1,desc='Health Care Services Delivery'),
          Segment( 'CRC', Properties(req_sit='S',repeat=1,desc='Patient Condition Information'),
          Segment( 'CL1', Properties(req_sit='S',repeat=1,desc='Institutional Claim Code'),
          Segment( 'CR1', Properties(req_sit='S',repeat=1,desc='Ambulance Transport Information'),
          Segment( 'CR2', Properties(req_sit='S',repeat=1,desc='Spinal Manipulation Service Information'),
          Segment( 'CR5', Properties(req_sit='S',repeat=1,desc='Home Oxygen Therapy Information'),
          Segment( 'CR6', Properties(req_sit='S',repeat=1,desc='Home Health Care Information'),
          Segment( 'MSG', Properties(req_sit='S',repeat=1,desc='Message Text'),
        ),
      ),
      Loop( 'SE', Properties(req_sit='R',repeat='1',desc='SE'),
        Segment( 'SE', Properties(),
      ),
    ),
    Loop( 'GE', Properties(req_sit='R',repeat='1',desc='GE'),
      Segment( 'GE', Properties(),
    ),
  ),
  Loop( 'IEA', Properties(req_sit='R',repeat='1',desc='IEA'),
    Segment( 'IEA', Properties(),
  ),
)
